### ISSUE TITLE
Minor issues when initializing kong palettes

### ISSUE THREAD

**Issue by H4v0c21** [H4v0c21/DKC-2-Project-Kongs#25]
If the leader kong is in slot 1 when retrieving a kong from a dk barrel they will also be assigned to slot 1.
Kong palettes aren't assigned properly on level load. Usually if the leader is the second kong.
These are likely already known issues but are just here for consistency.

**Comment by Mattrizzle** [comment]
With my latest pull request #35, the issues mentioned in the original comment have been resolved.

Issues when a Kong transforms into an Animal Buddy, Kong palette assignments in the Kong Family areas, and palette assignments for Diddy/Dixie barrels still need to be addressed.

For the first, the leader Kong's palette should always be preserved because it is used by the life counter icon, but currently it isn't because the transformed Animal Buddy takes over the leader Kong's palette line instead of the follower Kong's.  This not only causes issues with the life icon, but when transforming back into the Kongs.

**Comment by H4v0c21** [comment]
Marking this resolved. Any minor visual things related to this can be opened as separate issues with the new animation bug label and Cosmetic Kong Integration milestone.
