### ISSUE TITLE
Defeating Kleever causes the game to freeze

### ISSUE THREAD

**Issue by H4v0c21** [H4v0c21/DKC-2-Project-Kongs#28]
When Kleever's main body hits the lava after his death animation the game freezes.

**Comment by H4v0c21** [comment]
I've been working on this one for some time. Your theory seems plausible. My understanding is that something is happening before the crash to put the SPC into an unstable state. Then when the game sends any commands to it seems to cause the crash. If I NOP one routine causing the crash it just makes it further until another routine sends a command triggering a crash. Worth noting all of these crashes are happening at what I believe is a period in time before the transition music routine is called but I haven't confirmed this yet.

**Comment by Mattrizzle** [comment]
Upon closer inspection, the hang occurs when attempting to play a queued sound effect (routine $B5801E, 
play_queued_sound_effect). The particular sound effect value ($076A, or ID $6A played on channel 7) is for a bubbling one which supposed to play when Kleever hits the lava.  I was thinking the unstable SPC state may have been caused by an invalid sound effect value being used within one of Donkey Kong's animations, but the hang still happened when playing the full battle as Diddy/Dixie.

**Comment by H4v0c21** [comment]
Oldest appearance of this bug was in this commit: 2d732818b5ea1f266ffa8df150f294d7e2f35540.
However it's worth noting before this commit it was impossible to get to the end of the boss fight due to another glitch related to the cannon ball init scripts. This does however rule out all the changes we've done since 2/22/23 - 3/1/23.
