### ISSUE TITLE
Kreepy Krow intro softlocks game

### ISSUE THREAD

**Issue by H4v0c21** [H4v0c21/DKC-2-Project-Kongs#60]
Upon entering the Kreepy Krow boss fight as any kong when the kongs play their scared animation they teleport off screen and die. This causes a softlock.

**Comment by Mattrizzle** [comment]
Weird, as this worked in a previous commit, and nothing specific to this battle was changed.  A pointer somewhere must not be properly parsed as a label.

**Comment by Mattrizzle** [comment]
My fix for Issue #45 broke the Kreepy Krow battle.  This is because $0662 is actually used for something there.  As a result, the game tries to activate all four Kongs at once and the engine gets confused, resulting in a softlock. 

As for alternatives to $0662, $066E holds the value for what level you're on in the map.  Its value is zero when on a Kong Family or Klubba's Kiosk icon, but this isn't useful for the Cranky's Video Game Heroes screen, and it's also set to zero in boss levels.  The search for a good way to determine whether you're in a Kong helper area continues...

**Comment by H4v0c21** [comment]
We could also do a check on $D3 (level number) and BEQ

**Comment by Mattrizzle** [comment]
In the Monkey Museum ending cutscene after finishing Krocodile Kore, the level number isn't cleared, so it's still #$006B.  I suppose we could add code to set it to zero there too, though.

Some alternatives:
1. Check $1C (currently loaded song) for the values #$0004 (Swanky), #$0008 (Funky), #$000A (Klubba), #$000C (Wrinkly), or #$0019 (Cranky).  This would break things for people playing around with the music.
2. Create a flag in free RAM to set when entering one of these areas (including the cutscenes and Cranky's Video Game Heroes), and clear it when exiting.
